### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by dayanageeks** [Jnv821/4Geeks-IG-Photo-Feed-BS#1]
- [x]  EL botón de la ventana modal no  tiene el estilo correcto 
- [x]  EL estilo del dropdown le hace falta espacio por el lado derecho. 
- [x] El icono de instagram debe  tener un espacio con el texto

**Comment by Jnv821** [comment]
Las tres tareas han sido resueltas, el display de los post en los grids ha sido cambiado para ser más fiel al diseño original.
